### DISCUSSION TITLE
Vertical border lines in month view can't be changed

### DISCUSSION THREAD

**Discussion by oscar6662** [nhn/tui.calendar#1346] [Q&A] [answered]
## Version
 @toast-ui/react-calendar: ^2.1.3,

## Test Environment
locally. Both Safari and Google Chrome

## Current Behavior
When editing the border parameter in Theme->common only the horizontal lines change to the expected format. Vertical ones remain unchanged. I've tried all possible theme settings that include the border parameter and none changes the horizontal lines.
```js
            border: "1px solid rgb(64, 64, 71)",
```

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/16443844/211008838-db9f9573-ab8c-4e7d-be17-d8d98b32eee1.png">

## Expected Behavior
Can someone tell me how to change the horizontal grid lines? I've been trying for the past day all sorts of possibilities and it seems odd that it's this hard.

**Comment by adhrinae** [comment, marked as answer]
It's hardcoded in the CSS file.

https://github.com/nhn/tui.calendar/blob/main/apps/calendar/src/css/daygrid/dayGrid.css#L34-L36

You need to add the prefix to the classname when you overriding CSS.

```css
.toastui-calendar-daygrid-cell + .toastui-calendar-daygrid-cell {
	/* Change here */
    border-left: 1px solid #e5e5e5;
}
```
