### ISSUE TITLE
When v-show is used, calendar does not keep the height.

### ISSUE THREAD

**Issue by Tragio** [nhn/tui.calendar#1184]
## Version
JS v2.0.1

## Bug Report

In my current implementation, I import the Calendar module only on its component. Then I do an API fetch, when the fetch is done I enable it using `v-show` (it acts as `display: none`). However, height is never respected. But if you resize the window it resizes to the original height. I tried to use `calendar.render` after enabling the variable, but no effect.

In v1, I tweaked a bit the CSS so the calendar could be full height without scroll, so we don't have the scroll of the calendar and the page. It would be also awesome, to see how can it be achieved on v2.

https://codesandbox.io/s/tui-calendar-css-2orj0s?file=/components/Calendar.vue

Really thank you for the amazing work! 🥳

**Comment by Tragio** [comment]
@adhrinae thank you for your prompt reply 🙂 Hmmm yes, I understand. I refactored the code logic a little differently and now it works just fine.

The only thing I miss from v1 is a way to make it full height, so we don't have the scroll of both the calendar and the page.

This is how I've done it in v1:
```css
.tui-full-calendar-vlayout-area.tui-full-calendar-vlayout-container {
  height: 100% !important;
  > div:last-child {
    height: 100% !important;
  }
}
.tui-full-calendar-timegrid-container,
.tui-full-calendar-dayname-container,
.tui-full-calendar-weekday-grid,
.tui-full-calendar-weekday-schedules {
  overflow-y: auto !important;
}
```
