### ISSUE TITLE
timegridOneHour, timegridHalfHour and dayGridSchedule have no effect on the calendar

### ISSUE THREAD

**Issue by andrelung** [nhn/tui.calendar#1240]
## Version
 * TOAST UI Calendar 2nd Edition
 * @version 2.1.1 | Wed Aug 03 2022

## Test Environment
Chrome Version 104.0.5112.79 (arm64)
macOS Monterey Version 12.4 (21F79)

## Expected Behavior
I'd love to remove the scroll bars from within the calendar. My setup needs to show the whole calendar, so I set the following weekOptions:
    hourStart: 0,
    hourEnd: 24,

I expect the following setTheme-command to reduce the calendar-height:
```js
  // documentation: https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/theme.md
  cal.setTheme({
    common: {
      gridSelection: {
        backgroundColor: "rgba(81, 230, 92, 0.05)", // change color of transparency selection (just to check if this is generally working)
        border: "1px dotted #515ce6",
      },
    },
    week: { // <= these settings have no effect on the week or day view
      timegridOneHour: {
        height: "12px",
      },
      // timegridHalfHour: {
      //   height: "6px",
      // },
      dayGridSchedule: {
        height: "6px",
      },
    },
    // "week.timegridOneHour.height": "10px", // << also no effect
    // "week.timegridHalfHour.height": "5px" // << neither combined, nor in single use
  });
```
I also tried setting the options with only number values. No effect either

## Current Behavior
I can't figure out any change when settings these options. If these are the wrong settings, I'd love to get a nudge how to remove in-container-scrollbars (make the calendar fit it's container).

**Comment by adhrinae** [comment]
@andrelung 

## Reason

You're trying to use the `v1`'s theme, which significantly differs from the current version.

https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/theme.md#week-theme

[You can override CSS styles for your own use case](https://github.com/nhn/tui.calendar/blob/main/docs/en/guide/migration-guide-v2.md#theme-improvement), but we fixed the unit of the height of each row of the time grid as percentage(`%`) values.

## Solution

You can open the browser's devtools and find which element creates the scrollbar then override the stylesheet. That's what we intended, however, I'll leave the solution for documentation.

First, Let's override the `min-height` of the time grid panel.

```css
.toastui-calendar-timegrid {
  height: 100%;
  /* fit-content or auto(IE) */
  min-height: fit-content;
}
```

<img width="228" alt="image" src="https://user-images.githubusercontent.com/14539203/183317300-59777208-8d47-470f-9dcf-da333d9912dc.png">

But It still has a tiny scrollbar as well as other areas(we call them panels).

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/14539203/183317386-4f8d7ca1-1fbc-4c15-ba80-47a334c25290.png">

We intended that every panel should be aligned with the time grid having the scrollbar by default.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/14539203/183317594-78ed6f09-5c45-4de2-89ab-07a60e43baba.png">

But you're removing scrollbars so it doesn't have to right now.

```css
/* Declared class twice to increase the specificity. */
/* You can use the `!important` but not recommended */
.toastui-calendar-panel:not(.toastui-calendar-time).toastui-calendar-panel:not(.toastui-calendar-time) {
  overflow-y: hidden;
}

.toastui-calendar-panel.toastui-calendar-panel {
  overflow-y: hidden;
}
```

Now you can see the calendar without scrollbars.
Check out [this working example](https://stackblitz.com/edit/js-bmq8sr?file=style.css).
