### ISSUE TITLE
Set constrasting color for titles 

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#617]
focused schedules are always displayed with white text on the schedule’s color.  If the schedule is yellow, then the title is in white, and this is hard to read.

* Set somehow magically the color of the schedules’ title to be contrasting (in the month view).  E.g. on focused events in yellow, set the text to black.

**Comment by dongsik-yoo** [comment]
You can set colors. Check this [doc](https://nhn.github.io/tui.calendar/latest/Schedule), then you can use `color`, `bgColor` properties with `createSchedules` or `updateSchedule`.

**Comment by dilyanpalauzov** [comment]
https://github.com/nhn/tui.calendar/blob/master/src/js/view/template/month/weekdayInMonthSchedule.hbs#L45 contains:
```css
                    <span class="{{CSS_PREFIX}}weekday-schedule-title"
                        style="
                            {{#if model.isFocused}}
                                color: #ffffff;
                                background-color: {{model.color}}
                            {{else}}
                                color:#333;
                            {{/if}}
```
and the font color is always white on `model.color` background, which can be yellow.

Take as example the labels at https://github.com/nhn/tui.calendar/issues/474:

“Help wanted” is white text on blue background, so it has contrast.  The “Category: Options” label has black text on light backgroud, which is good. But the “Feature” label has black text on dark background, which is ... corner-case.  The “Bug” label at https://github.com/nhn/tui.calendar/issues/548 has black text on dark red background, which is hard to read.

https://gitlab.gnome.org/GNOME/evolution/-/blob/master/src/e-util/e-misc-utils.c#L1660 shows how to chose white or black for the text color, based on the background.
